# Generated by Django 5.2.4 on 2025-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
